- name: configure the frontend
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: delete the default website
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  - name: create the html diretory
    ansible.builtin.file:
      path: usr/share/nginx/html
      state: directory
  - name: download and extract the frontend code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  - name: coy backend config
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted